name: flutter_mdns_plugin
description: Flutter mDNS plugin
version: 0.0.1
author:
homepage:

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
  plugin:
    androidPackage: eu.sndr.fluttermdnsplugin
    pluginClass: FlutterMdnsPlugin
